// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBACZypZZbqLESnTovnynUSOokuxa0Busw',
    appId: '1:719002061183:web:d0cebae2d0190eaf82724a',
    messagingSenderId: '719002061183',
    projectId: 'note-3a1df',
    authDomain: 'note-3a1df.firebaseapp.com',
    storageBucket: 'note-3a1df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0qiAC9yDmbalr4I5kduIMKYaB0AnLoI',
    appId: '1:719002061183:android:14cef08b98fcff8582724a',
    messagingSenderId: '719002061183',
    projectId: 'note-3a1df',
    storageBucket: 'note-3a1df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZghSzBaDTSthIBq3Pb9H4cz8CSTYZqk',
    appId: '1:719002061183:ios:80fd3db60ef45d6c82724a',
    messagingSenderId: '719002061183',
    projectId: 'note-3a1df',
    storageBucket: 'note-3a1df.appspot.com',
    iosBundleId: 'com.example.notetaking',
  );
}
